name: "2nd-order-Heun-unconditional" #same as the file name, try to do that for all testers

tester:
  _target_: 'testing.tester.Tester'

sampler:
  _target_: 'testing.SamplerEulerHeun.SamplerEulerHeun'

modes: ["unconditional"] #modes to test

checkpoint: None


overriden_name: Null


sampling_params:
  same_as_training: False #if true, the sampling parameters will be the same as the ones used for training (sigma_data, sigma_min, sigma_max and rho)
  sde_hp:
    sigma_data: 0.063 #default for maestro
    sigma_min: 1e-5
    sigma_max: 8 #this is sigma_start
    rho: 10
  Schurn: 10
  Snoise: 1
  Stmin: 0
  Stmax: 10
  order: 2 #order of the sampler (1 or 2)
  T: 51 #number of discretization steprs
  schedule: "edm" #"log": log schedule using the parameters in sampling_params


#experiment configuration for different testing modes

unconditional:
  num_samples: 1
  batch_size: 4
  audio_len: 262144

wandb:
  use: False
